const languageSelect = document.getElementById('language-select');
const bootstrapStylesheet = document.getElementById('bootstrap-css');
const timelineCards = document.querySelectorAll('.card-copy');
const subscriptionForm = document.getElementById('subscribe-form');
const formStatus = document.getElementById('form-status');

const arabicText = {
  pageTitle: 'إنتل | الاستدامة عبر العصور',
  skipLink: 'انتقل إلى المحتوى الرئيسي',
  mainNavigation: 'التنقل الرئيسي',
  intelHome: 'الصفحة الرئيسية لشركة إنتل',
  intelLogo: 'شعار إنتل',
  navLabel: 'داخل الإشارة / ٠١',
  languageLabel: 'اختر اللغة / Choose language',
  exploreTimeline: 'استكشف الخط الزمني',
  heroEyebrow: 'أرشيف حي / ١٩٦٨ - ٢٠٢٤',
  heroTitle: 'التقدم يبدأ بالتغيير.',
  heroCopy: 'خط زمني للأشخاص والأنظمة والقرارات التي ساعدت إنتل على بناء مستقبل أكثر مسؤولية.',
  soundNote: 'استكشفوا على مهل. لا يتم تشغيل الصوت تلقائيًا.',
  scrollPrompt: 'مرروا للاستكشاف',
  milestoneCount: '٠٩ محطات',
  pillarsEyebrow: 'نحو مستقبل أكثر استدامة',
  pillarsTitle: 'التقدم في ثلاثة مسارات',
  pillarsIntro: 'يربط عملنا بين العمل المناخي والإدارة المسؤولة للمياه والحد من النفايات.',
  climateTitle: 'العمل المناخي',
  climateCopy: 'خفض الانبعاثات التشغيلية والعمل نحو تحقيق صافي انبعاثات غازات دفيئة صفرية بحلول عام ٢٠٤٠.',
  learnClimate: 'تعرفوا على هدف الحياد الصفري',
  waterTitle: 'الإدارة المسؤولة للمياه',
  waterCopy: 'الحفاظ على المياه وإعادتها إلى الأحواض المحلية ودعم المجتمعات.',
  learnWater: 'تعرفوا على أهدافنا',
  wasteTitle: 'الحد من النفايات',
  wasteCopy: 'الحد من النفايات وزيادة إعادة الاستخدام والتدوير في عملياتنا.',
  learnWaste: 'استكشفوا استراتيجية RISE',
  timelineEyebrow: 'الخط الزمني للاستدامة',
  timelineTitle: 'من الابتكار إلى التأثير',
  timelineHint: 'اختاروا محطة لإبرازها. مرروا أفقيًا لاستكشاف الخط الزمني كاملًا.',
  timelineLabel: 'الخط الزمني للاستدامة في إنتل',
  title1968: 'تأسيس إنتل',
  copy1968: 'غيّر روبرت نويس وغوردون مور اسم شركة NM Electronics إلى Intel Corporation، وأطلقا شركة تقوم على الابتكار والتفكير طويل الأمد.',
  title1971: 'أول معالج دقيق',
  copy1971: 'أطلقت إنتل 4004، أول معالج دقيق تجاري في العالم، وغيّرت بذلك طريقة وصول قدرات الحوسبة إلى الحياة اليومية.',
  title1978: 'المعالج 8086',
  copy1978: 'أصبح 8086 أساس بنية x86، وساعد على إتاحة حوسبة ميسورة التكلفة وأنظمة رقمية قابلة للتوسع.',
  title1985: 'المعالج 386',
  copy1985: 'قدّم معالج 386 من إنتل أداءً بمعمارية 32 بت، مما أتاح حواسيب شخصية أكثر قدرة وتجربة رقمية أغنى.',
  title2006: 'ذروة انبعاثات غازات الدفيئة',
  copy2006: 'سجلت إنتل أعلى انبعاثات تشغيلية سنوية لها، ثم استثمرت في خفض الانبعاثات والطاقة النظيفة وكفاءة التصنيع لعكس هذا الاتجاه.',
  title2020: 'استراتيجية RISE',
  copy2020: 'أطلقت إنتل استراتيجية RISE وأهداف 2030، وحددت مسارًا واضحًا للعمل المناخي والإدارة المسؤولة للمياه والحد من النفايات.',
  title2022: 'صافي انبعاثات صفري بحلول 2040',
  copy2022: 'التزمت إنتل بتحقيق صافي انبعاثات غازات دفيئة صفرية في عملياتها العالمية بحلول عام 2040.',
  title2023: 'الكهرباء المتجددة',
  copy2023: 'حققت إنتل استخدام كهرباء متجددة بنسبة 99٪ حول العالم، مما يقلل الانبعاثات ويدعم تصنيعًا أنظف.',
  title2024: 'قمة الاستدامة',
  copy2024: 'جمعت إنتل الموردين والقادة الحكوميين والشركاء للعمل معًا من أجل مستقبل أكثر استدامة لصناعة أشباه الموصلات.',
  alt1968: 'فريق إنتل أو لحظة تأسيس الشركة',
  alt1971: 'تصميم المعالجات الدقيقة وتصنيعها',
  alt1978: 'تطوير معمارية المعالجات والتقنيات',
  alt1985: 'أجهزة تقنية من إنتل في مصنع أو مختبر',
  alt2006: 'بيئة تصنيع وتحدٍ بيئي',
  alt2020: 'بحث واستراتيجية للأنظمة المستدامة',
  alt2022: 'التزام بالاستدامة ومبادرات بيئية',
  alt2023: 'طاقة متجددة واستثمارات في البنية التحتية',
  alt2024: 'قمة إنتل للاستدامة والتعاون',
  subscribeEyebrow: 'ابقوا على اطلاع',
  subscribeTitle: 'مستجدات الاستدامة تصلكم.',
  subscribeCopy: 'اشتركوا لتلقي أخبار دورية عن جهود إنتل في مجال الاستدامة.',
  emailLabel: 'عنوان البريد الإلكتروني',
  emailHelp: 'أدخلوا عنوان بريد إلكتروني صالحًا. هذا النموذج التجريبي لا يرسل معلوماتكم ولا يخزنها.',
  subscribeButton: 'اشتركوا',
  formStatus: 'شكرًا لكم. هذا النموذج جاهز للربط بخدمة نشرات بريدية؛ لم يُرسل عنوانكم أو يُخزن.',
  footerText: 'استدامة إنتل | نبني معًا مستقبلًا أكثر مسؤولية.',
  backToTop: 'العودة إلى الأعلى',
};

const translations = {
  ar: arabicText,
  ko: {
    pageTitle: 'Intel | 시대를 거쳐 온 지속 가능성',
    skipLink: '본문으로 건너뛰기',
    mainNavigation: '주요 탐색',
    intelHome: 'Intel 홈',
    intelLogo: 'Intel 로고',
    navLabel: '인사이드 더 시그널 / 01',
    languageLabel: '언어 선택',
    exploreTimeline: '타임라인 살펴보기',
    heroEyebrow: '살아 있는 기록 / 1968 - 2024',
    heroTitle: '진보는 변화에서 시작됩니다.',
    heroCopy: 'Intel이 더 책임감 있는 미래로 나아가도록 이끈 사람, 시스템, 결정의 타임라인입니다.',
    soundNote: '편하게 둘러보세요. 이 페이지에서는 오디오가 자동 재생되지 않습니다.',
    scrollPrompt: '스크롤하여 살펴보기',
    milestoneCount: '주요 사건 09개',
    pillarsEyebrow: '더 지속 가능한 미래를 향해',
    pillarsTitle: '세 가지 방향의 진보',
    pillarsIntro: '기후 행동, 수자원 관리, 폐기물 감축을 아우르는 활동을 소개합니다.',
    climateTitle: '기후 행동',
    climateCopy: '운영 배출량을 줄이고 2040년까지 온실가스 순배출 제로를 달성하기 위해 노력합니다.',
    learnClimate: '넷제로 목표 알아보기',
    waterTitle: '수자원 관리',
    waterCopy: '물을 절약하고 지역 유역에 환원하며 지역사회를 지원합니다.',
    learnWater: '목표 알아보기',
    wasteTitle: '폐기물 감축',
    wasteCopy: '폐기물을 줄이고 운영 전반에서 재사용과 재활용을 확대합니다.',
    learnWaste: 'RISE 전략 살펴보기',
    timelineEyebrow: '지속 가능성 타임라인',
    timelineTitle: '발명에서 영향으로',
    timelineHint: '사건을 선택해 강조해 보세요. 가로로 스크롤하면 전체 타임라인을 볼 수 있습니다.',
    timelineLabel: 'Intel 지속 가능성 타임라인',
    title1968: 'Intel 설립',
    copy1968: '로버트 노이스와 고든 무어는 NM Electronics의 이름을 Intel Corporation으로 바꾸고 혁신과 장기적 사고를 바탕으로 회사를 세웠습니다.',
    title1971: '최초의 마이크로프로세서',
    copy1971: 'Intel은 세계 최초의 상용 마이크로프로세서인 4004를 출시해 컴퓨팅 기술이 일상에 닿는 방식을 바꾸었습니다.',
    title1978: '8086 프로세서',
    copy1978: '8086은 x86 아키텍처의 기반이 되어 합리적인 컴퓨팅과 확장 가능한 디지털 시스템의 발전을 이끌었습니다.',
    title1985: '386 프로세서',
    copy1985: 'Intel 386 프로세서는 32비트 성능을 제공해 더 강력한 개인용 컴퓨터와 풍부한 디지털 경험을 가능하게 했습니다.',
    title2006: '온실가스 배출량 정점',
    copy2006: 'Intel은 운영 부문에서 연간 온실가스 배출량이 가장 높았으며, 이후 배출 저감과 청정에너지, 효율적인 제조에 투자했습니다.',
    title2020: 'RISE 전략',
    copy2020: 'Intel은 RISE 전략과 2030 목표를 발표하고 기후 행동, 수자원 관리, 폐기물 감축을 위한 계획을 세웠습니다.',
    title2022: '2040년 넷제로',
    copy2022: 'Intel은 2040년까지 전 세계 사업장에서 온실가스 순배출 제로를 달성하겠다고 약속했습니다.',
    title2023: '재생에너지 전력',
    copy2023: 'Intel은 전 세계에서 재생에너지 전력 사용률 99%를 달성해 배출량을 줄이고 더 깨끗한 제조를 지원했습니다.',
    title2024: '지속 가능성 서밋',
    copy2024: 'Intel은 공급업체, 정부 관계자, 파트너를 모아 더욱 지속 가능한 반도체 산업의 미래를 논의했습니다.',
    alt1968: 'Intel 팀 또는 창립 당시의 모습',
    alt1971: '마이크로프로세서 설계 및 제조',
    alt1978: '프로세서 아키텍처와 기술 개발',
    alt1985: '공장 또는 연구실의 Intel 기술 장비',
    alt2006: '제조 환경과 환경 문제',
    alt2020: '지속 가능한 시스템 연구와 전략',
    alt2022: '지속 가능성 약속과 친환경 활동',
    alt2023: '재생에너지와 인프라 투자',
    alt2024: 'Intel 지속 가능성 서밋과 협력',
    subscribeEyebrow: '새 소식 받기',
    subscribeTitle: '지속 가능성 소식을 받아보세요.',
    subscribeCopy: 'Intel의 지속 가능성 활동에 관한 소식을 가끔 이메일로 받아보세요.',
    emailLabel: '이메일 주소',
    emailHelp: '유효한 이메일 주소를 입력하세요. 이 데모는 정보를 전송하거나 저장하지 않습니다.',
    subscribeButton: '구독 신청',
    formStatus: '감사합니다. 이 데모는 뉴스레터 서비스 연결용이며 이메일은 전송되거나 저장되지 않았습니다.',
    footerText: 'Intel 지속 가능성 | 함께 더 책임감 있는 미래를 만들어 갑니다.',
    backToTop: '맨 위로',
  },
  ja: {
    pageTitle: 'Intel | 時代とともに歩むサステナビリティ',
    skipLink: 'メインコンテンツへ移動',
    mainNavigation: 'メインナビゲーション',
    intelHome: 'Intel ホーム',
    intelLogo: 'Intel ロゴ',
    navLabel: 'インサイド・ザ・シグナル / 01',
    languageLabel: '言語を選択',
    exploreTimeline: 'タイムラインを見る',
    heroEyebrow: '生きたアーカイブ / 1968 - 2024',
    heroTitle: '進歩は変化から始まります。',
    heroCopy: 'Intelをより責任ある未来へ導いてきた人々、システム、決断をたどるタイムラインです。',
    soundNote: 'ご自身のペースでご覧ください。このページでは音声は自動再生されません。',
    scrollPrompt: 'スクロールして見る',
    milestoneCount: '主な出来事 09件',
    pillarsEyebrow: 'より持続可能な未来へ',
    pillarsTitle: '3つの取り組み',
    pillarsIntro: '気候変動対策、水資源の保全、廃棄物の削減に取り組んでいます。',
    climateTitle: '気候変動対策',
    climateCopy: '事業活動による排出量を削減し、2040年までの温室効果ガス排出量ネットゼロを目指します。',
    learnClimate: 'ネットゼロ目標を見る',
    waterTitle: '水資源の保全',
    waterCopy: '水を節約し、地域の流域に還元するとともに、地域社会を支援します。',
    learnWater: '目標を見る',
    wasteTitle: '廃棄物の削減',
    wasteCopy: '廃棄物の発生を抑え、事業全体で再利用とリサイクルを推進します。',
    learnWaste: 'RISE戦略を見る',
    timelineEyebrow: 'サステナビリティの歩み',
    timelineTitle: '発明から社会への貢献へ',
    timelineHint: '出来事を選ぶと強調表示されます。横にスクロールして全体をご覧ください。',
    timelineLabel: 'Intelのサステナビリティ年表',
    title1968: 'Intel創業',
    copy1968: 'ロバート・ノイスとゴードン・ムーアはNM ElectronicsをIntel Corporationに改称し、革新と長期的な視点を重視する企業を築きました。',
    title1971: '世界初のマイクロプロセッサー',
    copy1971: 'Intelは世界初の商用マイクロプロセッサー4004を発表し、コンピューティングが日常に広がる道を切り開きました。',
    title1978: '8086プロセッサー',
    copy1978: '8086はx86アーキテクチャーの基礎となり、手頃なコンピューティングと拡張可能なデジタルシステムを支えました。',
    title1985: '386プロセッサー',
    copy1985: 'Intel 386は32ビット性能を実現し、より高性能なパーソナルコンピューターと豊かなデジタル体験を可能にしました。',
    title2006: '温室効果ガス排出量のピーク',
    copy2006: 'Intelの事業活動による年間温室効果ガス排出量が過去最高となり、その後、削減技術やクリーンエネルギー、効率的な製造に投資しました。',
    title2020: 'RISE戦略',
    copy2020: 'IntelはRISE戦略と2030年目標を発表し、気候変動対策、水資源の保全、廃棄物削減への道筋を示しました。',
    title2022: '2040年までのネットゼロ',
    copy2022: 'Intelは2040年までに世界の事業活動で温室効果ガス排出量ネットゼロを達成することを約束しました。',
    title2023: '再生可能電力',
    copy2023: 'Intelは世界全体で再生可能電力の使用率99%を達成し、排出量を減らしてよりクリーンな製造を進めました。',
    title2024: 'サステナビリティ・サミット',
    copy2024: 'Intelはサプライヤー、政府関係者、パートナーを集め、半導体業界のより持続可能な未来について話し合いました。',
    alt1968: 'Intelのチームまたは創業時の様子',
    alt1971: 'マイクロプロセッサーの設計と製造',
    alt1978: 'プロセッサーのアーキテクチャーと技術開発',
    alt1985: '工場または研究所にあるIntelの技術機器',
    alt2006: '製造環境と環境課題',
    alt2020: '持続可能なシステムの研究と戦略',
    alt2022: 'サステナビリティへの取り組みと環境施策',
    alt2023: '再生可能エネルギーとインフラへの投資',
    alt2024: 'Intelサステナビリティ・サミットと協業',
    subscribeEyebrow: '最新情報を受け取る',
    subscribeTitle: 'サステナビリティの最新情報をお届けします。',
    subscribeCopy: 'Intelのサステナビリティ活動に関するニュースをメールでお届けします。',
    emailLabel: 'メールアドレス',
    emailHelp: '有効なメールアドレスを入力してください。このデモでは情報を送信・保存しません。',
    subscribeButton: '登録する',
    formStatus: 'ありがとうございます。このデモはニュースレターサービスとの接続用です。メールは送信・保存されていません。',
    footerText: 'Intelのサステナビリティ | ともに、より責任ある未来を築きます。',
    backToTop: 'ページ上部へ',
  },
  zh: {
    pageTitle: 'Intel | 跨越时代的可持续发展',
    skipLink: '跳转到主要内容',
    mainNavigation: '主导航',
    intelHome: 'Intel 首页',
    intelLogo: 'Intel 标志',
    navLabel: '信号内侧 / 01',
    languageLabel: '选择语言',
    exploreTimeline: '探索时间线',
    heroEyebrow: '持续更新的档案 / 1968 - 2024',
    heroTitle: '进步，始于改变。',
    heroCopy: '了解推动 Intel 迈向更负责任未来的人物、体系与决策。',
    soundNote: '请按自己的节奏浏览。本页面不会自动播放音频。',
    scrollPrompt: '滚动探索',
    milestoneCount: '09 个里程碑',
    pillarsEyebrow: '迈向更可持续的未来',
    pillarsTitle: '三个方向的进步',
    pillarsIntro: '我们的工作涵盖气候行动、水资源管理和减少废弃物。',
    climateTitle: '气候行动',
    climateCopy: '减少运营排放，努力在 2040 年前实现温室气体净零排放。',
    learnClimate: '了解净零目标',
    waterTitle: '水资源管理',
    waterCopy: '节约用水、补充当地流域水资源，并支持社区发展。',
    learnWater: '了解我们的目标',
    wasteTitle: '减少废弃物',
    wasteCopy: '从源头减少废弃物，并在运营中提高再利用和回收比例。',
    learnWaste: '探索 RISE 战略',
    timelineEyebrow: '可持续发展时间线',
    timelineTitle: '从发明到影响',
    timelineHint: '选择一个里程碑以突出显示。横向滚动可查看完整时间线。',
    timelineLabel: 'Intel 可持续发展时间线',
    title1968: 'Intel 成立',
    copy1968: '罗伯特·诺伊斯和戈登·摩尔将 NM Electronics 更名为 Intel Corporation，创立了一家注重创新与长远发展的公司。',
    title1971: '首款微处理器',
    copy1971: 'Intel 推出全球首款商用微处理器 4004，改变了计算能力走进日常生活的方式。',
    title1978: '8086 处理器',
    copy1978: '8086 成为 x86 架构的基础，推动了经济实用的计算和可扩展数字系统的发展。',
    title1985: '386 处理器',
    copy1985: 'Intel 386 处理器带来 32 位性能，让功能更强大的个人电脑和更丰富的数字体验成为可能。',
    title2006: '温室气体排放峰值',
    copy2006: 'Intel 的年度运营温室气体排放量达到最高水平，随后投资于减排、清洁能源和高效制造以扭转趋势。',
    title2020: 'RISE 战略',
    copy2020: 'Intel 发布 RISE 战略和 2030 年目标，为气候行动、水资源管理和减少废弃物制定了明确方向。',
    title2022: '2040 年实现净零排放',
    copy2022: 'Intel 承诺到 2040 年在全球运营中实现温室气体净零排放。',
    title2023: '可再生电力',
    copy2023: 'Intel 的全球可再生电力使用率达到 99%，减少排放并推动更清洁的制造。',
    title2024: '可持续发展峰会',
    copy2024: 'Intel 汇集供应商、政府领导人和合作伙伴，共同探讨半导体行业更可持续的未来。',
    alt1968: 'Intel 团队或公司创立场景',
    alt1971: '微处理器设计与制造',
    alt1978: '处理器架构与技术开发',
    alt1985: '工厂或实验室中的 Intel 技术设备',
    alt2006: '制造环境与环境挑战',
    alt2020: '可持续系统研究与战略',
    alt2022: '可持续发展承诺与绿色举措',
    alt2023: '可再生能源与基础设施投资',
    alt2024: 'Intel 可持续发展峰会与合作',
    subscribeEyebrow: '获取最新动态',
    subscribeTitle: '订阅可持续发展动态。',
    subscribeCopy: '订阅后可不定期收到 Intel 可持续发展工作的相关消息。',
    emailLabel: '电子邮箱地址',
    emailHelp: '请输入有效的电子邮箱地址。本演示不会发送或存储您的信息。',
    subscribeButton: '订阅',
    formStatus: '谢谢！此演示表单可接入新闻邮件服务；您的邮箱尚未发送或存储。',
    footerText: 'Intel 可持续发展 | 携手共建更负责任的未来。',
    backToTop: '返回顶部',
  },
  es: {
    pageTitle: 'Intel | Sostenibilidad a través del tiempo',
    skipLink: 'Saltar al contenido principal',
    mainNavigation: 'Navegación principal',
    intelHome: 'Inicio de Intel',
    intelLogo: 'Logotipo de Intel',
    navLabel: 'Dentro de la señal / 01',
    languageLabel: 'Elegir idioma',
    exploreTimeline: 'Explorar cronología',
    heroEyebrow: 'Un archivo vivo / 1968 - 2024',
    heroTitle: 'El progreso empieza con el cambio.',
    heroCopy: 'Una cronología de las personas, los sistemas y las decisiones que impulsan a Intel hacia un futuro más responsable.',
    soundNote: 'Explora a tu ritmo. Esta experiencia no reproduce audio automáticamente.',
    scrollPrompt: 'Desplázate para explorar',
    milestoneCount: '09 hitos',
    pillarsEyebrow: 'Hacia un futuro más sostenible',
    pillarsTitle: 'Progreso en tres ámbitos',
    pillarsIntro: 'Nuestro trabajo conecta la acción climática, la gestión del agua y la reducción de residuos.',
    climateTitle: 'Acción climática',
    climateCopy: 'Reducimos las emisiones operativas y avanzamos hacia cero emisiones netas de gases de efecto invernadero para 2040.',
    learnClimate: 'Más información sobre cero emisiones netas',
    waterTitle: 'Gestión del agua',
    waterCopy: 'Conservamos agua, la devolvemos a las cuencas locales y apoyamos a las comunidades.',
    learnWater: 'Más información sobre nuestros objetivos',
    wasteTitle: 'Reducción de residuos',
    wasteCopy: 'Reducimos los residuos y aumentamos la reutilización y el reciclaje en nuestras operaciones.',
    learnWaste: 'Explorar la estrategia RISE',
    timelineEyebrow: 'Cronología de sostenibilidad',
    timelineTitle: 'De la invención al impacto',
    timelineHint: 'Selecciona un hito para destacarlo. Desplázate horizontalmente para ver toda la cronología.',
    timelineLabel: 'Cronología de sostenibilidad de Intel',
    title1968: 'Fundación de Intel',
    copy1968: 'Robert Noyce y Gordon Moore cambian el nombre de NM Electronics a Intel Corporation y crean una empresa basada en la innovación y la visión a largo plazo.',
    title1971: 'Primer microprocesador',
    copy1971: 'Intel lanza el 4004, el primer microprocesador comercial del mundo, y transforma el acceso cotidiano a la informática.',
    title1978: 'Procesador 8086',
    copy1978: 'El 8086 se convierte en la base de la arquitectura x86 y ayuda a impulsar la informática asequible y los sistemas digitales escalables.',
    title1985: 'Procesador 386',
    copy1985: 'El procesador 386 de Intel ofrece rendimiento de 32 bits y permite computadoras personales más capaces y una experiencia digital más completa.',
    title2006: 'Máximo de emisiones de GEI',
    copy2006: 'Las emisiones anuales de gases de efecto invernadero de las operaciones de Intel alcanzan su máximo; después, la empresa invierte en reducción de emisiones, energía limpia y fabricación eficiente.',
    title2020: 'Estrategia RISE',
    copy2020: 'Intel presenta su estrategia RISE y sus objetivos para 2030, con una hoja de ruta para la acción climática, el agua y los residuos.',
    title2022: 'Cero emisiones netas para 2040',
    copy2022: 'Intel se compromete a lograr cero emisiones netas de gases de efecto invernadero en sus operaciones globales para 2040.',
    title2023: 'Electricidad renovable',
    copy2023: 'Intel alcanza un 99 % de electricidad renovable en todo el mundo, reduciendo emisiones y promoviendo una fabricación más limpia.',
    title2024: 'Cumbre de sostenibilidad',
    copy2024: 'Intel reúne a proveedores, responsables públicos y socios para impulsar juntos un futuro más sostenible para los semiconductores.',
    alt1968: 'Equipo de Intel o momento de su fundación',
    alt1971: 'Diseño y fabricación de microprocesadores',
    alt1978: 'Arquitectura de procesadores y desarrollo tecnológico',
    alt1985: 'Tecnología de Intel en una fábrica o laboratorio',
    alt2006: 'Entorno de fabricación y reto medioambiental',
    alt2020: 'Investigación y estrategia para sistemas sostenibles',
    alt2022: 'Compromiso con la sostenibilidad e iniciativas ecológicas',
    alt2023: 'Energía renovable e inversión en infraestructura',
    alt2024: 'Cumbre de sostenibilidad de Intel y colaboración',
    subscribeEyebrow: 'Mantente al día',
    subscribeTitle: 'Novedades de sostenibilidad en tu correo.',
    subscribeCopy: 'Recibe noticias ocasionales sobre el trabajo de Intel en sostenibilidad.',
    emailLabel: 'Correo electrónico',
    emailHelp: 'Introduce una dirección de correo válida. Esta demostración no envía ni guarda tu información.',
    subscribeButton: 'Suscribirme',
    formStatus: '¡Gracias! Esta demostración está lista para conectarse a un servicio de boletines; tu correo no se ha enviado ni guardado.',
    footerText: 'Sostenibilidad de Intel | Construimos juntos un futuro más responsable.',
    backToTop: 'Volver arriba',
  },
  fr: {
    pageTitle: 'Intel | Le développement durable à travers le temps',
    skipLink: 'Aller au contenu principal',
    mainNavigation: 'Navigation principale',
    intelHome: 'Accueil Intel',
    intelLogo: 'Logo Intel',
    navLabel: 'Au cœur du signal / 01',
    languageLabel: 'Choisir la langue',
    exploreTimeline: 'Explorer la chronologie',
    heroEyebrow: 'Une histoire vivante / 1968 - 2024',
    heroTitle: 'Le progrès commence par le changement.',
    heroCopy: 'Une chronologie des personnes, des systèmes et des décisions qui font avancer Intel vers un avenir plus responsable.',
    soundNote: 'Explorez à votre rythme. Cette page ne lance aucun son automatiquement.',
    scrollPrompt: 'Faites défiler pour explorer',
    milestoneCount: '09 étapes clés',
    pillarsEyebrow: 'Vers un avenir plus durable',
    pillarsTitle: 'Le progrès dans trois domaines',
    pillarsIntro: 'Nos actions associent lutte contre le changement climatique, gestion de l’eau et réduction des déchets.',
    climateTitle: 'Action climatique',
    climateCopy: 'Réduire les émissions de nos activités et viser zéro émission nette de gaz à effet de serre d’ici 2040.',
    learnClimate: 'En savoir plus sur le zéro net',
    waterTitle: 'Gestion de l’eau',
    waterCopy: 'Préserver l’eau, la restituer aux bassins locaux et soutenir les communautés.',
    learnWater: 'Découvrir nos objectifs',
    wasteTitle: 'Réduction des déchets',
    wasteCopy: 'Réduire les déchets et développer le réemploi et le recyclage dans nos activités.',
    learnWaste: 'Explorer la stratégie RISE',
    timelineEyebrow: 'Chronologie du développement durable',
    timelineTitle: 'De l’invention à l’impact',
    timelineHint: 'Sélectionnez une étape pour la mettre en évidence. Faites défiler horizontalement pour parcourir toute la chronologie.',
    timelineLabel: 'Chronologie du développement durable d’Intel',
    title1968: 'Création d’Intel',
    copy1968: 'Robert Noyce et Gordon Moore rebaptisent NM Electronics Intel Corporation et fondent une entreprise portée par l’innovation et la vision à long terme.',
    title1971: 'Premier microprocesseur',
    copy1971: 'Intel lance le 4004, le premier microprocesseur commercial au monde, transformant l’accès quotidien à l’informatique.',
    title1978: 'Processeur 8086',
    copy1978: 'Le 8086 devient le fondement de l’architecture x86 et contribue à rendre l’informatique abordable et évolutive.',
    title1985: 'Processeur 386',
    copy1985: 'Le processeur Intel 386 apporte les performances 32 bits et permet des ordinateurs personnels plus puissants et une expérience numérique enrichie.',
    title2006: 'Pic des émissions de GES',
    copy2006: 'Les émissions annuelles de gaz à effet de serre des activités d’Intel atteignent un sommet, puis l’entreprise investit dans leur réduction, les énergies propres et l’efficacité de la fabrication.',
    title2020: 'Stratégie RISE',
    copy2020: 'Intel lance sa stratégie RISE et ses objectifs 2030, avec une feuille de route pour le climat, l’eau et la réduction des déchets.',
    title2022: 'Zéro émission nette d’ici 2040',
    copy2022: 'Intel s’engage à atteindre zéro émission nette de gaz à effet de serre dans ses activités mondiales d’ici 2040.',
    title2023: 'Électricité renouvelable',
    copy2023: 'Intel atteint 99 % d’électricité renouvelable dans le monde, réduisant les émissions et favorisant une fabrication plus propre.',
    title2024: 'Sommet sur le développement durable',
    copy2024: 'Intel réunit fournisseurs, responsables publics et partenaires pour bâtir ensemble un avenir plus durable pour les semi-conducteurs.',
    alt1968: 'Équipe Intel ou moment de la fondation',
    alt1971: 'Conception et fabrication de microprocesseurs',
    alt1978: 'Architecture de processeurs et développement technologique',
    alt1985: 'Équipements technologiques Intel dans une usine ou un laboratoire',
    alt2006: 'Environnement de fabrication et défi environnemental',
    alt2020: 'Recherche et stratégie pour des systèmes durables',
    alt2022: 'Engagement en faveur du développement durable et initiatives écologiques',
    alt2023: 'Énergies renouvelables et investissement dans les infrastructures',
    alt2024: 'Sommet Intel sur le développement durable et collaboration',
    subscribeEyebrow: 'Restez informé',
    subscribeTitle: 'Recevez nos actualités sur le développement durable.',
    subscribeCopy: 'Recevez ponctuellement des nouvelles sur les actions d’Intel en matière de développement durable.',
    emailLabel: 'Adresse e-mail',
    emailHelp: 'Saisissez une adresse e-mail valide. Cette démonstration n’envoie ni ne stocke vos informations.',
    subscribeButton: 'S’inscrire',
    formStatus: 'Merci ! Cette démonstration peut être reliée à un service de newsletter ; votre adresse n’a pas été envoyée ni enregistrée.',
    footerText: 'Développement durable chez Intel | Construire ensemble un avenir plus responsable.',
    backToTop: 'Retour en haut',
  },
  it: {
    pageTitle: 'Intel | Sostenibilità nel corso del tempo',
    skipLink: 'Vai al contenuto principale',
    mainNavigation: 'Navigazione principale',
    intelHome: 'Home Intel',
    intelLogo: 'Logo Intel',
    navLabel: 'Dentro il segnale / 01',
    languageLabel: 'Scegli la lingua',
    exploreTimeline: 'Esplora la cronologia',
    heroEyebrow: 'Un archivio vivo / 1968 - 2024',
    heroTitle: 'Il progresso inizia dal cambiamento.',
    heroCopy: 'Una cronologia delle persone, dei sistemi e delle decisioni che guidano Intel verso un futuro più responsabile.',
    soundNote: 'Esplora con calma. Questa esperienza non riproduce audio automaticamente.',
    scrollPrompt: 'Scorri per esplorare',
    milestoneCount: '09 tappe',
    pillarsEyebrow: 'Verso un futuro più sostenibile',
    pillarsTitle: 'Il progresso in tre ambiti',
    pillarsIntro: 'Il nostro impegno collega azione per il clima, gestione dell’acqua e riduzione dei rifiuti.',
    climateTitle: 'Azione per il clima',
    climateCopy: 'Ridurre le emissioni operative e puntare a zero emissioni nette di gas serra entro il 2040.',
    learnClimate: 'Scopri l’obiettivo zero emissioni',
    waterTitle: 'Gestione dell’acqua',
    waterCopy: 'Risparmiare acqua, restituirla ai bacini idrografici locali e sostenere le comunità.',
    learnWater: 'Scopri i nostri obiettivi',
    wasteTitle: 'Riduzione dei rifiuti',
    wasteCopy: 'Ridurre i rifiuti e aumentare il riutilizzo e il riciclo nelle nostre attività.',
    learnWaste: 'Esplora la strategia RISE',
    timelineEyebrow: 'Cronologia della sostenibilità',
    timelineTitle: 'Dall’invenzione all’impatto',
    timelineHint: 'Seleziona una tappa per evidenziarla. Scorri in orizzontale per esplorare l’intera cronologia.',
    timelineLabel: 'Cronologia della sostenibilità Intel',
    title1968: 'Nasce Intel',
    copy1968: 'Robert Noyce e Gordon Moore rinominano NM Electronics in Intel Corporation, creando un’azienda fondata sull’innovazione e su una visione a lungo termine.',
    title1971: 'Primo microprocessore',
    copy1971: 'Intel lancia il 4004, il primo microprocessore commerciale al mondo, cambiando il modo in cui la potenza di calcolo entra nella vita quotidiana.',
    title1978: 'Processore 8086',
    copy1978: 'L’8086 diventa la base dell’architettura x86 e contribuisce a rendere l’informatica accessibile e i sistemi digitali scalabili.',
    title1985: 'Processore 386',
    copy1985: 'Il processore Intel 386 introduce prestazioni a 32 bit, consentendo PC più potenti e un’esperienza digitale più ricca.',
    title2006: 'Picco delle emissioni di gas serra',
    copy2006: 'Le emissioni operative annuali di gas serra di Intel raggiungono il massimo; in seguito l’azienda investe in riduzione delle emissioni, energia pulita e produzione efficiente.',
    title2020: 'Strategia RISE',
    copy2020: 'Intel lancia la strategia RISE e gli obiettivi 2030, definendo un percorso per il clima, l’acqua e la riduzione dei rifiuti.',
    title2022: 'Zero emissioni nette entro il 2040',
    copy2022: 'Intel si impegna a raggiungere zero emissioni nette di gas serra nelle proprie attività globali entro il 2040.',
    title2023: 'Energia elettrica rinnovabile',
    copy2023: 'Intel raggiunge il 99% di elettricità rinnovabile nel mondo, riducendo le emissioni e promuovendo una produzione più pulita.',
    title2024: 'Vertice sulla sostenibilità',
    copy2024: 'Intel riunisce fornitori, rappresentanti governativi e partner per costruire insieme un futuro più sostenibile per i semiconduttori.',
    alt1968: 'Team Intel o momento della fondazione',
    alt1971: 'Progettazione e produzione di microprocessori',
    alt1978: 'Architettura dei processori e sviluppo tecnologico',
    alt1985: 'Tecnologie Intel in fabbrica o in laboratorio',
    alt2006: 'Ambiente di produzione e sfida ambientale',
    alt2020: 'Ricerca e strategia per sistemi sostenibili',
    alt2022: 'Impegno per la sostenibilità e iniziative ecologiche',
    alt2023: 'Energia rinnovabile e investimenti nelle infrastrutture',
    alt2024: 'Vertice Intel sulla sostenibilità e collaborazione',
    subscribeEyebrow: 'Resta aggiornato',
    subscribeTitle: 'Ricevi aggiornamenti sulla sostenibilità.',
    subscribeCopy: 'Ricevi occasionalmente notizie sull’impegno di Intel per la sostenibilità.',
    emailLabel: 'Indirizzo e-mail',
    emailHelp: 'Inserisci un indirizzo e-mail valido. Questa demo non invia né memorizza i tuoi dati.',
    subscribeButton: 'Iscriviti',
    formStatus: 'Grazie! Questa demo è pronta per essere collegata a un servizio newsletter; la tua e-mail non è stata inviata né salvata.',
    footerText: 'Sostenibilità Intel | Costruiamo insieme un futuro più responsabile.',
    backToTop: 'Torna all’inizio',
  },
  ru: {
    pageTitle: 'Intel | Устойчивое развитие сквозь время',
    skipLink: 'Перейти к основному содержимому',
    mainNavigation: 'Главная навигация',
    intelHome: 'Главная страница Intel',
    intelLogo: 'Логотип Intel',
    navLabel: 'Внутри сигнала / 01',
    languageLabel: 'Выберите язык',
    exploreTimeline: 'Открыть хронологию',
    heroEyebrow: 'Живая история / 1968–2024',
    heroTitle: 'Прогресс начинается с перемен.',
    heroCopy: 'Хронология людей, систем и решений, которые помогают Intel двигаться к более ответственному будущему.',
    soundNote: 'Изучайте страницу в удобном темпе. Звук не запускается автоматически.',
    scrollPrompt: 'Прокрутите, чтобы изучить',
    milestoneCount: '09 важных событий',
    pillarsEyebrow: 'На пути к устойчивому будущему',
    pillarsTitle: 'Прогресс в трёх направлениях',
    pillarsIntro: 'Наша работа объединяет борьбу с изменением климата, рациональное использование воды и сокращение отходов.',
    climateTitle: 'Борьба с изменением климата',
    climateCopy: 'Мы сокращаем выбросы в своей деятельности и стремимся к нулевым чистым выбросам парниковых газов к 2040 году.',
    learnClimate: 'Подробнее о цели нулевых выбросов',
    waterTitle: 'Рациональное использование воды',
    waterCopy: 'Мы экономим воду, возвращаем её в местные водосборные бассейны и поддерживаем сообщества.',
    learnWater: 'Подробнее о наших целях',
    wasteTitle: 'Сокращение отходов',
    wasteCopy: 'Мы сокращаем количество отходов, расширяя повторное использование и переработку.',
    learnWaste: 'О стратегии RISE',
    timelineEyebrow: 'Хронология устойчивого развития',
    timelineTitle: 'От изобретений к результатам',
    timelineHint: 'Выберите событие, чтобы выделить его. Прокрутите по горизонтали, чтобы посмотреть всю хронологию.',
    timelineLabel: 'Хронология устойчивого развития Intel',
    title1968: 'Основание Intel',
    copy1968: 'Роберт Нойс и Гордон Мур переименовали NM Electronics в Intel Corporation, создав компанию, основанную на инновациях и долгосрочном мышлении.',
    title1971: 'Первый микропроцессор',
    copy1971: 'Intel выпустила 4004 — первый в мире коммерческий микропроцессор, изменив доступность вычислительных технологий в повседневной жизни.',
    title1978: 'Процессор 8086',
    copy1978: '8086 стал основой архитектуры x86 и помог сделать вычислительную технику доступнее, а цифровые системы — масштабируемее.',
    title1985: 'Процессор 386',
    copy1985: 'Процессор Intel 386 с 32-разрядной производительностью позволил создавать более мощные персональные компьютеры.',
    title2006: 'Пик выбросов парниковых газов',
    copy2006: 'Годовые выбросы парниковых газов от деятельности Intel достигли максимума; затем компания инвестировала в их сокращение, чистую энергию и эффективное производство.',
    title2020: 'Стратегия RISE',
    copy2020: 'Intel представила стратегию RISE и цели на 2030 год, определив планы по климату, водным ресурсам и сокращению отходов.',
    title2022: 'Нулевые выбросы к 2040 году',
    copy2022: 'Intel обязалась достичь нулевых чистых выбросов парниковых газов в своей деятельности по всему миру к 2040 году.',
    title2023: 'Электроэнергия из возобновляемых источников',
    copy2023: 'Доля электроэнергии из возобновляемых источников в Intel достигла 99% во всём мире, что помогает сокращать выбросы.',
    title2024: 'Саммит по устойчивому развитию',
    copy2024: 'Intel объединила поставщиков, представителей власти и партнёров для совместной работы над устойчивым будущим полупроводниковой отрасли.',
    alt1968: 'Команда Intel или момент основания компании',
    alt1971: 'Проектирование и производство микропроцессоров',
    alt1978: 'Архитектура процессоров и разработка технологий',
    alt1985: 'Технологическое оборудование Intel на заводе или в лаборатории',
    alt2006: 'Производственная среда и экологическая проблема',
    alt2020: 'Исследования и стратегия устойчивых систем',
    alt2022: 'Обязательства в области устойчивого развития и экологические инициативы',
    alt2023: 'Возобновляемая энергия и инвестиции в инфраструктуру',
    alt2024: 'Саммит Intel по устойчивому развитию и сотрудничество',
    subscribeEyebrow: 'Будьте в курсе',
    subscribeTitle: 'Новости об устойчивом развитии — вам на почту.',
    subscribeCopy: 'Получайте периодические новости о работе Intel в области устойчивого развития.',
    emailLabel: 'Адрес электронной почты',
    emailHelp: 'Введите действительный адрес электронной почты. Эта демонстрационная форма не отправляет и не сохраняет данные.',
    subscribeButton: 'Подписаться',
    formStatus: 'Спасибо! Эту демонстрационную форму можно подключить к сервису рассылок; ваш адрес не был отправлен или сохранён.',
    footerText: 'Устойчивое развитие Intel | Вместе строим более ответственное будущее.',
    backToTop: 'Вернуться наверх',
  },
  de: {
    pageTitle: 'Intel | Nachhaltigkeit im Wandel der Zeit',
    skipLink: 'Zum Hauptinhalt springen',
    mainNavigation: 'Hauptnavigation',
    intelHome: 'Intel-Startseite',
    intelLogo: 'Intel-Logo',
    navLabel: 'Im Zeichen des Signals / 01',
    languageLabel: 'Sprache auswählen',
    exploreTimeline: 'Zeitleiste erkunden',
    heroEyebrow: 'Ein lebendiges Archiv / 1968–2024',
    heroTitle: 'Fortschritt beginnt mit Veränderung.',
    heroCopy: 'Eine Zeitleiste der Menschen, Systeme und Entscheidungen, die Intel auf dem Weg in eine verantwortungsvollere Zukunft geprägt haben.',
    soundNote: 'Entdecken Sie die Seite in Ihrem eigenen Tempo. Es wird kein Audio automatisch abgespielt.',
    scrollPrompt: 'Zum Entdecken scrollen',
    milestoneCount: '09 Meilensteine',
    pillarsEyebrow: 'Auf dem Weg in eine nachhaltigere Zukunft',
    pillarsTitle: 'Fortschritt in drei Bereichen',
    pillarsIntro: 'Unsere Arbeit verbindet Klimaschutz, verantwortungsvollen Umgang mit Wasser und Abfallvermeidung.',
    climateTitle: 'Klimaschutz',
    climateCopy: 'Wir senken betriebliche Emissionen und streben bis 2040 Netto-Null-Treibhausgasemissionen an.',
    learnClimate: 'Mehr zum Netto-Null-Ziel',
    waterTitle: 'Verantwortungsvoller Umgang mit Wasser',
    waterCopy: 'Wir sparen Wasser, führen es lokalen Wassereinzugsgebieten zurück und unterstützen Gemeinden.',
    learnWater: 'Mehr zu unseren Zielen',
    wasteTitle: 'Abfallvermeidung',
    wasteCopy: 'Wir vermeiden Abfall und fördern Wiederverwendung und Recycling in unseren Betriebsabläufen.',
    learnWaste: 'RISE-Strategie erkunden',
    timelineEyebrow: 'Zeitleiste der Nachhaltigkeit',
    timelineTitle: 'Von der Erfindung zur Wirkung',
    timelineHint: 'Wählen Sie einen Meilenstein aus, um ihn hervorzuheben. Scrollen Sie horizontal, um die gesamte Zeitleiste zu erkunden.',
    timelineLabel: 'Intel-Zeitleiste zur Nachhaltigkeit',
    title1968: 'Intel wird gegründet',
    copy1968: 'Robert Noyce und Gordon Moore benennen NM Electronics in Intel Corporation um und gründen ein Unternehmen, das auf Innovation und langfristiges Denken setzt.',
    title1971: 'Erster Mikroprozessor',
    copy1971: 'Intel bringt den 4004 auf den Markt, den weltweit ersten kommerziellen Mikroprozessor, und verändert damit den Zugang zu Computerleistung im Alltag.',
    title1978: '8086-Prozessor',
    copy1978: 'Der 8086 wird zur Grundlage der x86-Architektur und ermöglicht erschwingliche Computer und skalierbare digitale Systeme.',
    title1985: '386-Prozessor',
    copy1985: 'Der Intel 386 bietet 32-Bit-Leistung und ermöglicht leistungsfähigere PCs und ein vielfältigeres digitales Erlebnis.',
    title2006: 'Höchststand der Treibhausgasemissionen',
    copy2006: 'Die jährlichen betrieblichen Treibhausgasemissionen von Intel erreichen ihren Höchststand. Anschließend investiert das Unternehmen in Emissionsminderung, saubere Energie und effiziente Fertigung.',
    title2020: 'RISE-Strategie',
    copy2020: 'Intel stellt seine RISE-Strategie und Ziele für 2030 vor und legt einen klaren Weg für Klimaschutz, Wasserverantwortung und Abfallvermeidung fest.',
    title2022: 'Netto-Null bis 2040',
    copy2022: 'Intel verpflichtet sich, bis 2040 weltweit Netto-Null-Treibhausgasemissionen im eigenen Betrieb zu erreichen.',
    title2023: 'Erneuerbare Elektrizität',
    copy2023: 'Intel erreicht weltweit einen Anteil von 99 % erneuerbarer Elektrizität und senkt so Emissionen für eine sauberere Fertigung.',
    title2024: 'Nachhaltigkeitsgipfel',
    copy2024: 'Intel bringt Zulieferer, Regierungsvertreter und Partner zusammen, um gemeinsam eine nachhaltigere Zukunft für die Halbleiterbranche zu gestalten.',
    alt1968: 'Intel-Team oder Moment der Unternehmensgründung',
    alt1971: 'Entwicklung und Fertigung von Mikroprozessoren',
    alt1978: 'Prozessorarchitektur und Technologieentwicklung',
    alt1985: 'Intel-Technologie in einer Fabrik oder einem Labor',
    alt2006: 'Fertigungsumgebung und ökologische Herausforderung',
    alt2020: 'Forschung und Strategie für nachhaltige Systeme',
    alt2022: 'Nachhaltigkeitsverpflichtung und Umweltinitiativen',
    alt2023: 'Erneuerbare Energie und Infrastrukturinvestitionen',
    alt2024: 'Intel-Nachhaltigkeitsgipfel und Zusammenarbeit',
    subscribeEyebrow: 'Auf dem Laufenden bleiben',
    subscribeTitle: 'Nachhaltigkeitsneuigkeiten direkt in Ihr Postfach.',
    subscribeCopy: 'Erhalten Sie gelegentlich Neuigkeiten zu Intels Nachhaltigkeitsarbeit.',
    emailLabel: 'E-Mail-Adresse',
    emailHelp: 'Geben Sie eine gültige E-Mail-Adresse ein. Diese Demo sendet oder speichert Ihre Angaben nicht.',
    subscribeButton: 'Anmelden',
    formStatus: 'Vielen Dank! Diese Demo kann mit einem Newsletterdienst verbunden werden; Ihre E-Mail wurde nicht gesendet oder gespeichert.',
    footerText: 'Intel Nachhaltigkeit | Gemeinsam eine verantwortungsvollere Zukunft gestalten.',
    backToTop: 'Zurück nach oben',
  },
};

function applyLanguage(language) {
  const languageText = translations[language] || {};
  const isArabic = language === 'ar';
  const direction = isArabic ? 'rtl' : 'ltr';

  document.documentElement.lang = language;
  document.documentElement.dir = direction;
  bootstrapStylesheet.href = isArabic
    ? 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.rtl.min.css'
    : 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css';

  document.querySelectorAll('[data-i18n]').forEach((element) => {
    if (!element.dataset.englishText) {
      element.dataset.englishText = element.textContent.trim();
    }

    element.textContent = languageText[element.dataset.i18n] || element.dataset.englishText;
  });

  document.querySelectorAll('[data-i18n-aria]').forEach((element) => {
    const key = element.dataset.i18nAria;
    if (!element.dataset.englishAria) {
      element.dataset.englishAria = element.getAttribute('aria-label');
    }

    element.setAttribute(
      'aria-label',
      languageText[key] || element.dataset.englishAria,
    );
  });

  document.querySelectorAll('[data-i18n-alt]').forEach((element) => {
    const key = element.dataset.i18nAlt;
    if (!element.dataset.englishAlt) {
      element.dataset.englishAlt = element.alt;
    }

    element.alt = languageText[key] || element.dataset.englishAlt;
  });

  document.title = languageText.pageTitle || 'Intel | Sustainability Through the Ages';
}

languageSelect.addEventListener('change', () => {
  applyLanguage(languageSelect.value);
  formStatus.textContent = '';
});

timelineCards.forEach((card) => {
  card.addEventListener('click', () => {
    const isExpanded = card.classList.contains('expanded');
    timelineCards.forEach((item) => {
      item.classList.remove('expanded');
      item.setAttribute('aria-pressed', 'false');
    });

    if (!isExpanded) {
      card.classList.add('expanded');
      card.setAttribute('aria-pressed', 'true');
    }
  });
});

subscriptionForm.addEventListener('submit', (event) => {
  event.preventDefault();

  if (!subscriptionForm.reportValidity()) {
    return;
  }

  formStatus.textContent = translations[languageSelect.value]?.formStatus
    || 'Thanks! This demo is ready to connect to a newsletter service; your email was not sent or stored.';
});

subscriptionForm.addEventListener('input', () => {
  formStatus.textContent = '';
});

// Match the visitor's browser language on first load; the selector can change it any time.
const supportedLanguages = [...languageSelect.options].map((option) => option.value);
const browserLanguage = navigator.language.toLowerCase().split('-')[0];
const initialLanguage = supportedLanguages.includes(browserLanguage) ? browserLanguage : 'en';

languageSelect.value = initialLanguage;
applyLanguage(initialLanguage);
